### ISSUE TITLE
[BUG] GPS 10-bit week rollover bug / Weak / No GPS

### ISSUE THREAD

**Issue by Git-tara** [universal5433/android_device_samsung_trelte-common#32] opened 2023-07-15 10:25 UTC
**Describe the bug**
GPS not available. Does not track current location

**To Reproduce**

Install and use any apps that uses GPS location. 

**Expected behavior**

Should be able to locate current position

**Screenshots**

Not needed.

**Smartphone model (please complete the following information):**
 - Galaxy Note 4 N910C

**Additional context**
- injecting gps data & time using gps fix or gps status does not fix the issue
- factory resetting the phone does not resolve this either

Thank you and more power!

**Comment by ananjaser1211** [comment] 2023-08-09 15:29
Hello, Thank you for the report, Apologies for the late reply ive been very occupied.

if possible could you check these two apps for what they report while being outdoors.

https://play.google.com/store/apps/details?id=com.chartcross.gpstest&hl=en_IN (check if it detects any satellites, if so how many, and if it gets GNSS Fix or just stays orange)

Download and check this app https://github.com/barbeau/gpstest/releases, it will show you how many satellites are visible, and if your GPS time is correct or not, at some point in 2019~2022 many devices were affected by a GPS 10-BIT rollout bug that broke GPS time, samsung did push updates to fix it for the note 5 and newer, i am not sure if the note 4 ever received that update, but it uses the same GPS chip as the note 5 and galaxy S7, both of which needed a patch on my other ROMs, other devices such as the note 8 , S9 also required an update.

it may be possible that our note 4 needed an update too.

Now that i check samsungs OTA notice page, i do see this, in august 2022 the device had an OTA update (with newer bootloader and modem too it seems)

![image](https://github.com/universal5433/android_device_samsung_trelte-common/assets/25624482/8760a3ad-daed-42f2-9fa4-9ce4140c1aae)

The note 5 got a similar notice, and i know for a fact that the note 5 needed this update to bring back GPS support

![image](https://github.com/universal5433/android_device_samsung_trelte-common/assets/25624482/4eb1f48b-b8b3-4445-8b41-8793cdb7e1ce)

Now here is the kicker, i have downloaded all the note 4 firmwares hosted on samfirm last year to update my bootloader and modem repo, however it seems that they no longer update the note 4 listings as this particular firmware (N910CXXU2DVG1) is missing

I am having issues downloading it from samfirm so i need to check for alternative way, i wonder if this is an OTA only update ?

![image](https://github.com/universal5433/android_device_samsung_trelte-common/assets/25624482/5078ff2a-addf-406a-acc3-618783ff4b5f)

i will see how i can get it, and with any luck it has newer GPS blobs inside

https://github.com/ananjaser1211/FloydQ_Reports/issues/296 for more information about this rollout bug, you can read this bug report on my other ROM

**Comment by ananjaser1211** [comment] 2023-08-09 19:39
Alright, i have confirmed that indeed it is a 10BIT rollover bug, and the new firmware N910CXXU2DVG1 is only available by OTA, it also updates the ~bootloader~ and modem, so i will try to extract it and put it on the WiKi,

![Update](https://github.com/universal5433/android_device_samsung_trelte-common/assets/25624482/0caef9d3-0ebd-456c-b4b5-09c7595acba5)

the update file does contain a patch to the gps HAL, so hopefully ill be able to test it on lineage OS and see if it fixes the BUG, to confirm i ran a test before flashing the OTA, While it does provide GNSS Fix, you can see that the number of satellites are very little, which means it is unable to connect to other satalites, possibly due to the rollover bug. in theory the update should fix this and it should be able to use more GPS satellites improving accuracy, as apps also do check GPS time and fail if its too old

![Screenshot_2023-08-09-23-13-26](https://github.com/universal5433/android_device_samsung_trelte-common/assets/25624482/3758acc9-8b5f-4153-97b4-757cf77aed0f)
![Screenshot_2023-08-09-23-13-21](https://github.com/universal5433/android_device_samsung_trelte-common/assets/25624482/da652b81-2336-4d99-82e0-ecb0dae5af23)
![Screenshot_2023-08-09-23-13-36](https://github.com/universal5433/android_device_samsung_trelte-common/assets/25624482/9c1def45-14f4-495d-a151-26afb0fde125)

**Comment by ananjaser1211** [comment] 2023-08-09 20:06
Indeed after the patch, the satellites in view reached as high as 20, and averaged around 16~18 in use, i.e its now using more satellites for location, the accuracy was also consistent at 16/8 while previously it reached as high as 64. further more the GPS reported time is now accurate. i will add the new libraries to the next builds of lineage as soon as possible.

![Screenshot_2023-08-09-23-59-35](https://github.com/universal5433/android_device_samsung_trelte-common/assets/25624482/794c5f64-4983-4c40-a097-6947c8acaeee)

![Screenshot_2023-08-10-00-00-21](https://github.com/universal5433/android_device_samsung_trelte-common/assets/25624482/13f7d9a1-cbc9-46f4-8c97-1bd9418f5790)

**Comment by ananjaser1211** [comment] 2023-08-11 06:19
I have applied the new blobs to lineage OS and the GPS time issue is fixed, attached is before and after the patch.

Note : the first time it runs it will take a minute or so until it syncs up with GPS time, then the rest of the satalites will appear, the same behavior's happened on stock after the update, after that gps ran without a hitch regardless of a reboot / toggling location etc, Thanks again for the report, the fix will be in the next set of lineage builds.

Before :
![pre](https://github.com/universal5433/android_device_samsung_trelte-common/assets/25624482/4d294a0a-aa15-405c-b44b-efaf47f07781)

After :
![post](https://github.com/universal5433/android_device_samsung_trelte-common/assets/25624482/541c33c3-fc87-442d-87eb-d0f44e399e65)

**Comment by Git-tara** [comment] 2023-08-11 14:34
I can't imagine the effort you put onto this project keeping this phone alive. I look forward on the next update. Thanks!!

**Comment by johnwalked** [comment] 2023-08-11 15:04
@Git-tara test

**Comment by johnwalked** [comment] 2023-08-11 15:06
@Git-tara Thats just pure fix great work anan as always!

**Closed as completed** 2023-08-11 23:26 UTC
Labels: bug, Fixed in next release
